language: "en-US"
reviews:
  auto_review:
    enabled: true
    base_branches:
      - master
      - main
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  path_instructions: []
chat:
  auto_reply: true
